# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 552)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setStyleSheet("background-color: #2c3136")
        self.centralwidget.setObjectName("centralwidget")
        self.text_1 = QtWidgets.QLabel(self.centralwidget)
        self.text_1.setGeometry(QtCore.QRect(30, 120, 211, 26))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text_1.setFont(font)
        self.text_1.setStyleSheet("color: white")
        self.text_1.setObjectName("text_1")
        self.input_text = QtWidgets.QLineEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(10, 150, 371, 211))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_text.setFont(font)
        self.input_text.setStyleSheet("background-color: #2c3136;\n"
"border: 2px solid #f66867;\n"
"border-radius: 10px;\n"
"color: white\n"
"\n"
"")
        self.input_text.setText("")
        self.input_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.input_text.setObjectName("input_text")
        self.output_translation = QtWidgets.QLineEdit(self.centralwidget)
        self.output_translation.setGeometry(QtCore.QRect(420, 150, 371, 211))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.output_translation.setFont(font)
        self.output_translation.setStyleSheet("background-color: #2c3136;\n"
"border: 2px solid #f66867;\n"
"border-radius: 10px;\n"
"color: white\n"
"\n"
"")
        self.output_translation.setText("")
        self.output_translation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.output_translation.setObjectName("output_translation")
        self.translate_button = QtWidgets.QPushButton(self.centralwidget)
        self.translate_button.setGeometry(QtCore.QRect(310, 390, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.translate_button.setFont(font)
        self.translate_button.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: #fc2847;\n"
"border-radius: 10;\n"
"display: block;\n"
"transition: transform .6s ease;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #f8173e;\n"
"border: 2px solid #f66867\n"
"}\n"
"\n"
"")
        self.translate_button.setObjectName("translate_button")
        self.text_2 = QtWidgets.QLabel(self.centralwidget)
        self.text_2.setGeometry(QtCore.QRect(580, 510, 221, 33))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.text_2.setFont(font)
        self.text_2.setStyleSheet("color: white")
        self.text_2.setObjectName("text_2")
        self.text_3 = QtWidgets.QLabel(self.centralwidget)
        self.text_3.setGeometry(QtCore.QRect(440, 120, 171, 26))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text_3.setFont(font)
        self.text_3.setStyleSheet("color: white")
        self.text_3.setObjectName("text_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(200, 125, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: #2c3136;\n"
"border: 2px solid #f66867;\n"
"border-radius: 10px;\n"
"color: white")
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(610, 125, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: #2c3136;\n"
"border: 2px solid #f66867;\n"
"border-radius: 10px;\n"
"color: white")
        self.comboBox_2.setObjectName("comboBox_2")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "SmartTranslator"))
        self.text_1.setText(_translate("mainWindow", "Выберите язык:"))
        self.translate_button.setText(_translate("mainWindow", "Перевести"))
        self.text_2.setText(_translate("mainWindow", "Smart Translator"))
        self.text_3.setText(_translate("mainWindow", "Выберите язык:"))
